# Generated by Django 6.0.3 on 2026-03-31 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('naturalidade', models.CharField(max_length=100)),
                ('origem', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('time', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], max_length=10)),
            ],
        ),
    ]
